"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _dashboard_summary from './dashboard-summary.bones.json'

configureBoneyard({"color":"rgba(0,0,0,0.06)","animate":"shimmer"})

registerBones({
  "dashboard-summary": _dashboard_summary,
})
